version: '3'

volumes:
  db-data:

services:
  app:
    container_name: app
    build: ./docker/php
    volumes:
      - ./src:/var/www
    depends_on:
      - db2

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: postgres:13.3
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment: # Set the postgres user name, password and database name.
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: c9
      TZ: Asia/Tokyo
    hostname: db
    restart: always

  db2:
    image: mysql:5.7
    container_name: db2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: c9
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  node:
    image: node:12.13-alpine
    container_name: node
    tty: true
    volumes:
      - ./src:/var/www
    working_dir: /var/www
